name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0,15,30,45 * * * *'
    # scheduled every 15 minutes (to test)
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Merge Upstream
        uses: Cubik65536/merge-upstream@v1.1.3
        with:
          upstream: PaperMC/Paper
          upstream-branch: master
          branch: master
          email: cobra1989@gmail.com
          name: Zignixx
          token: ${{ secrets.TOKEN }}