# PaperSand Auto compile
#

name: Build/Test Paper
on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.3.5
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Set outputs
              id: vars
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew build --stacktrace
            - name: Compile jar files
              run: |
                  ./gradlew paperclipJar --stacktrace
            - name: Create artifact folder
              run: mkdir artifact
            - name: Copy jar file to artifact folder
              uses: canastro/copy-file-action@master
              with:
                  source: "build/libs/Paper-1.17.1-R0.1-SNAPSHOT.jar"
                  target: "artifact/PaperSandServer-1.17.1-${{ steps.vars.outputs.sha_short }}.jar"
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with: 
                  name: PaperSand-1.17.1-${{ steps.vars.outputs.sha_short }}
                  path: artifact