# PaperSand Auto compile + setup a development release
#

name: Build/Test Paper - Release a development version
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.3.5
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew build --stacktrace
            - name: Compile jar files
              run: |
                  ./gradlew paperclipJar --stacktrace
            - name: Create artifact folder
              run: mkdir artifact
            - name: Copy jar file to artifact folder
              uses: canastro/copy-file-action@master
              with:
                  source: "build/libs/Paper-1.17.1-R0.1-SNAPSHOT.jar"
                  target: "artifact/PaperSandServer-1.17.1-${{ github.run_number }}.jar"
            - name: release
              uses: actions/create-release@v1
              id: create_release
              with:
                  draft: false
                  prerelease: false
                  release_name: Development Build - ${{ github.run_number }}
                  tag_name: v${{ github.run_number }}
                  body_path: PRERELEASE.md
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - name: Upload Artifact to Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifact/PaperSandServer-1.17.1-${{ github.run_number }}.jar
                  asset_name: PaperSandServer-1.17.1-${{ github.run_number }}.jar
                  asset_content_type: application/java-archive
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with: 
                  name: PaperSand-1.17.1-${{ github.run_number }}
                  path: artifact