# PaperSand Auto compile + setup a development release
#

name: Build/Test Paper - Release a development version
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.3.5
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: "3.7"
            - name: Patch and Build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew build --stacktrace
            - name: Compile jar files
              run: |
                  ./gradlew paperclipJar --stacktrace
            - name: Create Artifact Folder
              run: mkdir artifact
            - name: Fetch Jar File
              id: pl
              uses: Rishabh510/Path-lister-action@master
              with:
                  path: "build/libs/"
                  type: ".jar"

            - name: Output results
              id: vars
              run: |
                  echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
                  for i in ${{ steps.pl.outputs.paths }}; do
                  echo "::set-output name=destinationFileName::$i"
                  echo $i
                  done
                  echo ${{ steps.vars.outputs.destinationFileName }}
            - name: Format Filename Part 1
              uses: mad9000/actions-find-and-replace-string@1
              id: findandreplace
              with:
                  source: ${{ steps.vars.outputs.destinationFileName }}
                  find: 'build/libs//Paper-'
                  replace: ''
              
            - name: Format Filename Part 2
              uses: mad9000/actions-find-and-replace-string@1
              id: findandreplace2
              with:
                  source: ${{ steps.findandreplace.outputs.value }}
                  find: '-R0.1-SNAPSHOT.jar'
                  replace: ''
            - name: Test Output
              run: | 
                echo "The replaced value is ${{ steps.findandreplace2.outputs.value }}"
                echo "::set-output name=destinationFileNameVersion::${{ steps.findandreplace2.outputs.value }}"
            - name: Copy jar file to artifact folder
              uses: canastro/copy-file-action@master
              with:
                  source: "build/libs/Paper-${{ steps.vars.outputs.destinationFileNameVersion }}-R0.1-SNAPSHOT.jar"
                  target: "artifact/PaperSandServer-${{ steps.vars.outputs.destinationFileNameVersion }}-v${{ github.run_number }}.jar"
            - name: Create GitHub Release
              uses: actions/create-release@v1
              id: create_release
              with:
                  draft: false
                  prerelease: false
                  release_name: ${{ steps.vars.outputs.destinationFileNameVersion }} v${{ github.run_number }} - Development Build
                  tag_name: ${{ steps.vars.outputs.destinationFileNameVersion }} v${{ github.run_number }}
                  body_path: PRERELEASE.md
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - name: Upload Artifact to Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./artifact/PaperSandServer-${{ steps.vars.outputs.destinationFileNameVersion }}-v${{ github.run_number }}.jar
                  asset_name: PaperSandServer-${{ steps.vars.outputs.destinationFileNameVersion }}-v${{ github.run_number }}.jar
                  asset_content_type: application/java-archive
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with: 
                  name: PaperSand-${{ steps.vars.outputs.destinationFileNameVersion }}-v${{ github.run_number }}
                  path: artifact