# Here lie dragons!
#
# Note that there is no artifact step in this script. We do not want Paperclip
# jars to be built for every push & PR; our CI handles pushes to branches, while
# PRs can themselves link to Paperclip jars if it is necessary. Official such
# PRs will take use of testing builds.

name: Build Paper
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.3.5
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2.3.1
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew build --stacktrace
            - name: Compile jar files
              run: |
                  ./gradlew reobfJar --stacktrace
            - name: Create artifact folder
              run: mkdir artifact
            - name: Copy jar file to artifact folder
              uses: canastro/copy-file-action@master
              with:
                  source: "Paper-Server/build/libs/Paper-Server-reobf.jar"
                  target: "artifact/PaperSandServer.jar"
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with: 
                  name: PaperSand ${{ github.sha::6 }}
                  path: artifact
